**List**

In [1]:
#list type
x = ["apple", "banana", "berry", 45, 56.7, True]
print(x)
print(type(x))

# accessing elements
print(x[0])
print(x[4])

# modifying elements
x[0] = "Mango"
print(x)

['apple', 'banana', 'berry', 45, 56.7, True]
<class 'list'>
apple
56.7
['Mango', 'banana', 'berry', 45, 56.7, True]


**Tuple**

In [2]:
#tuple type
x = ("apple", "banana", "berry", 45, 56.7, True)
print(x)
print(type(x))

# accessing elements
print(x[0])
print(x[4])

# modifying elements/not possible imutable
x[0] = "Mango"
print(x)

('apple', 'banana', 'berry', 45, 56.7, True)
<class 'tuple'>
apple
56.7


TypeError: 'tuple' object does not support item assignment

**Iterating**

In [3]:
#list type
x = ["apple", "banana", "berry", 45, 56.7, True]

i = 0
while i < len(x):
  print(x[i])
  i = i + 1

print()

for i in range(len(x)):
  print(x[i])

print()

for item in x:
  print(item)






apple
banana
berry
45
56.7
True

apple
banana
berry
45
56.7
True

apple
banana
berry
45
56.7
True


**Slicing**

In [4]:
#list type
x = ["apple", "banana", "berry", 45, 56.7, True]

print(x[0:2])
print(x[1:3])

print(x[2:])
print(x[:4])

print(x[0:5])
print(x[0:5:2])

['apple', 'banana']
['banana', 'berry']
['berry', 45, 56.7, True]
['apple', 'banana', 'berry', 45]
['apple', 'banana', 'berry', 45, 56.7]
['apple', 'berry', 56.7]


**string type**

In [5]:
x = "Python-For-Artificial-Intelligence"

print(x[0:2])
print(x[1:3])

print(x[2:])
print(x[:4])

print(x[0:5])
print(x[0:5:2])

Py
yt
thon-For-Artificial-Intelligence
Pyth
Pytho
Pto


**Dictionary**

In [6]:
thisdict = {"id" : 100, "name" : "Saman", "salary" : 50000.0}

print(thisdict)

# Accessing elements
print(thisdict["id"])
print(thisdict["name"])
print(thisdict["salary"])

#Adding elements
thisdict["bonus"] = 10000
print(thisdict)

#modifying elements
thisdict["salary"] = 60000.0
print(thisdict)

#modifying elements
thisdict["Bonus"] = 20000.0
print(thisdict)

#adding other collections
thisdict["address"] = {"no" : 51, "street" : "1st lane", "town" : "kandy"}
thisdict["mobile"] = ["0718921122", "0723232222"]

print(thisdict)

# town
print(thisdict["address"])
print(thisdict["address"]["town"])

# 2nd mobile number
print(thisdict["mobile"])
print(thisdict["mobile"][1])

{'id': 100, 'name': 'Saman', 'salary': 50000.0}
100
Saman
50000.0
{'id': 100, 'name': 'Saman', 'salary': 50000.0, 'bonus': 10000}
{'id': 100, 'name': 'Saman', 'salary': 60000.0, 'bonus': 10000}
{'id': 100, 'name': 'Saman', 'salary': 60000.0, 'bonus': 10000, 'Bonus': 20000.0}
{'id': 100, 'name': 'Saman', 'salary': 60000.0, 'bonus': 10000, 'Bonus': 20000.0, 'address': {'no': 51, 'street': '1st lane', 'town': 'kandy'}, 'mobile': ['0718921122', '0723232222']}
{'no': 51, 'street': '1st lane', 'town': 'kandy'}
kandy
['0718921122', '0723232222']
0723232222


**Range**

In [7]:
x = range(10)
print(x)
for no in x:
  print(no)

print()
x = range(10, 20)
print(x)
for no in x:
  print(no)

print()
x = range(10, 20, 2)
print (x)
for no in x:
  print(no)



for no in range(10):
  print(no)

for no in range(10,20):
  print(no)

for no in range(10, 20, 2):
  print(no)

range(0, 10)
0
1
2
3
4
5
6
7
8
9

range(10, 20)
10
11
12
13
14
15
16
17
18
19

range(10, 20, 2)
10
12
14
16
18
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
10
12
14
16
18


**Numpy**

In [8]:
#importing NumPy
import numpy as np # We are giving an alias to numpy as np, this is a general standard
a = np.array([1,2,3,4,5]) # defines a numpy array, here data have to be the same type
print(a)
# 2D Arrays
# more than one dimensions
a = np.array([[1, 2], [3, 4],[5,6]])
print (a)

# dtype parameter
a = np.array([1, 2, 3, 4, 5], dtype = float)
# here the data type of the array
# is given as float
print (a)

# Shape function
a = np.array([[1,2,3],[4,5,6]])
print(a.shape) # Dimensions of the array
# (2, 3) - 2D Array - with 2 rows and 3 columns each

a = np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]],
               [[13,14,15], [16,17,18]],
               [[17,18,19],[20,21,22]]])
print(a.shape) # Dimensions of the array
# (4,2,3) - 3D array as dimensions 4, 2, 3

# printing specific values
print(a[0]) # First element
print(a[1]) # Second element
print(a[0][0]) # First Dimension, 1st element
print(a[0][1]) # First Dimension, 2nd element
print(a[0][0][0]) # First Dimension, 1st element, 1st value
print(a[0][0][1]) # First Dimension, 1st element, 2nd value
print(a[0][0][2]) # First Dimension, 1st element, 3rd value

# Reshaping Arrays
# You can change the number of dimensions in the array
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print (b)
c = a.reshape(6)
print(c)

# A 2D array initialized to zero
x = np.zeros([10,5], dtype = int)
print (x)

# A 2D array initialized to ones
x = np.ones([10,5], dtype = int)
print (x)

# generate an array with start and stop parameters set
x = np.arange(10,20,2)
print (x)

# generate an array of evenly spaced numbers between a given range
x = np.linspace(10,20,5)
print (x)

# Slicing
mylist = np.array([10,20,30,40,50,60,70,80,90,100])
print(mylist)
print(mylist[1]) # second element in array
print(mylist[2:5]) # prints 3rd, 4th and 5th elements in the array
print(mylist[2:]) # print all the elements from the 3rd element
print(mylist[:5]) # print all the elements upto the 5th element
print(mylist[len(mylist)-1])
print(mylist[-1])
print(mylist[-(len(mylist))])

# Array Manipulations
# In python you can perform direct array
#.  operations unlike other programming
#.  languages

a = np.array([10,20,30,40,50])
b = np.array([2, 3, 4, 5, 6])
c = a + b
print(c)
c = a - b
print(c)
c = a * b
print(c)
c = a / b
print(c)
c = a * 2
print(c)
c = a * 2 + 5
print(c)
c = b ** 2
print(c)

print(a.sum())
print(a.min())
print(a.max())
print(a.mean())




[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]
[1. 2. 3. 4. 5.]
(2, 3)
(4, 2, 3)
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[1 2 3]
[4 5 6]
1
2
3
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[10 12 14 16 18]
[10.  12.5 15.  17.5 20. ]
[ 10  20  30  40  50  60  70  80  90 100]
20
[30 40 50]
[ 30  40  50  60  70  80  90 100]
[10 20 30 40 50]
100
100
10
[12 23 34 45 56]
[ 8 17 26 35 44]
[ 20  60 120 200 300]
[5.         6.66666667 7.5        8.         8.33333333]
[ 20  40  60  80 100]
[ 25  45  65  85 105]
[ 4  9 16 25 36]
150
10
50
30.0


**Function**

In [9]:
def hello():
  print("Hello World")

def add(no1, no2):
  return no1 + no2

def divmod(no1, no2):
  return no1 // no2, no1 % no2

hello()
print(add(5,2))
a, b = divmod(10,3)
print (a)
print (b)


def divmod(no1, no2):
  return no1 // no2, no1 % no2

a, b = divmod(10,3)




Hello World
7
3
1


**Modules**

In [24]:
#importing a module
#import the module test as t

import test as t
t.hello()
a, b, c, d = t.calc(40,2)
print(a)
print(b)
print(c)
print(d)


#importing a specific function and giving it an alias
from test import hello as greet
greet()


AttributeError: module 'test' has no attribute 'hello'

In [12]:
#importing a class
from Person import Person
p1 = Person("Nimal", 23)
p1.myfunc()

#importing a class
from Person import Person as P
p1 = P("Rajitha", 19)
p1.myfunc()

mylist = [Person("Ajith", 23), Person("Amali",18)]

for x in mylist:
  x.myfunc()

ModuleNotFoundError: No module named 'Person'

In [13]:

mylist = []
for r in range(10):
  mylist.append(r)
print(mylist)

mylist2 = [n for n in range(10)]
print(mylist2)

mylist2 = [2*n+1 for n in range(10)]
print(mylist2)

mylist2 = [2*n for n in range(10,100,5)]
print(mylist2)

mylist = [10, 45, 22, 89, 55, 34, 90 ]

y = [no for no in mylist if no >= 50]
print(y)

import numpy as np
myarr = np.array([1,2,3,4,5])
b = [2 * no for no in myarr]
print(b)

def genPowLists(start, end):
  x = np.array([no for no in range(start, end+1)])
  y = x ** 2
  return (x, y)


(a, b) = genPowLists(2,9)
print(a)
print(b)

k = genPowLists(10,13)
print(k[0])
print(k[1])




[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190]
[89, 55, 90]
[np.int64(2), np.int64(4), np.int64(6), np.int64(8), np.int64(10)]
[2 3 4 5 6 7 8 9]
[ 4  9 16 25 36 49 64 81]
[10 11 12 13]
[100 121 144 169]


**Tensorflow**

In [14]:

import tensorflow as tf

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train, x_test = x_train / 255.0, x_test / 255.0


model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])



11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


**isEqual**

In [15]:
x = ["apple", "banana"]
y = ["apple", "banana"]
z = x

print(x is z)

# returns True because z is the same object as x

print(x is y)

# returns False because x is not the same object as y, even if they have the same content

print(x == y)

# to demonstrate the difference betweeen "is" and "==": this comparison returns True because x is equal to y



True
False
True


In [16]:
#list type
x = ["apple", "banana", "berry", 45, 56.7, True]
print(x)
print(type(x))

#tuple type
x = ("apple", "banana", "cherry", 45, 56.7, True)
print(x)
print(type(x))

x = range(6)
print(x) # range type
print(type(x))

y=tuple(x)
print(y) # typle type
print(type(y))

z=list(x)
print(z) # list type
print(type(z))

# show imutability of tuples

x = ["apple", "banana", "berry", 45, 56.7, True]
y = ("apple", "banana", "berry", 45, 56.7, True)
print(x)
print(y)
x[1] = "Mango"
print(x)
#y[1] = "Mango" # generates an error

# accessing list and tuples element by element

for item in x:
  print(item)

for item in y:
  print(item)

# combining lists together
z = ["honda", "toyota", "tesla"]
x = x + z
print(x)

z = ("honda", "toyota", "tesla")
y = y + z
print(y)

# Basic list operations
thislist = ["apple", "banana", "cherry"]
print(thislist[0])
print(thislist[1])
mylist = [10,20,30,40,50,60,70,80,90,100]
print(mylist)
print(mylist[1]) # second element in list
print(mylist[2:5]) # prints 3rd, 4th and 5th elements in the list
print(mylist[2:]) # print all the elements from the 3rd element
print(mylist[:5]) # print all the elements upto the 5th element



['apple', 'banana', 'berry', 45, 56.7, True]
<class 'list'>
('apple', 'banana', 'cherry', 45, 56.7, True)
<class 'tuple'>
range(0, 6)
<class 'range'>
(0, 1, 2, 3, 4, 5)
<class 'tuple'>
[0, 1, 2, 3, 4, 5]
<class 'list'>
['apple', 'banana', 'berry', 45, 56.7, True]
('apple', 'banana', 'berry', 45, 56.7, True)
['apple', 'Mango', 'berry', 45, 56.7, True]
apple
Mango
berry
45
56.7
True
apple
banana
berry
45
56.7
True
['apple', 'Mango', 'berry', 45, 56.7, True, 'honda', 'toyota', 'tesla']
('apple', 'banana', 'berry', 45, 56.7, True, 'honda', 'toyota', 'tesla')
apple
banana
[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
20
[30, 40, 50]
[30, 40, 50, 60, 70, 80, 90, 100]
[10, 20, 30, 40, 50]
